# Generated by Django 4.2.2 on 2023-06-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_userprofile_nid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(upload_to='D:\\Face Similarity Estimation\\ecommerce_hub\\store\\static\\product_images')),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
    ]
