# Generated by Django 4.2.2 on 2023-06-19 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_purchase_user_remove_order_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
